export const GET_CANDIDATES = 'GET_CANDIDATES';
export const FILTER_CANDIDATES = 'FILTER_CANDIDATES';
export const TOGGLE_ARCHIVED = 'TOGGLE_ARCHIVED';
export const TOGGLE_CANDIDATE_ARCHIVE_STATUS =
  'TOGGLE_CANDIDATE_ARCHIVE_STATUS';
